name: deploy on push (prod)
on:
    push:
        branches:
            - prod

jobs:
    deploy-app:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code to build on server
              uses: actions/checkout@v3
            - name: Copy file to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.PROD_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_KEY }}
                  source: "./html/*"
                  target: "/var/www/html"
                  strip_components: 1
